[package]
name = "wynd"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
comfy-table = "7.1.3"
const_format = "0.2.34"
reedline = "0.38.0"
slab = "0.4.9"
thiserror = "2.0.9"
void = "1.0.2"
